# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-11 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0007_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimg',
            field=models.FileField(blank=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
