# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 06:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0012_notification_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
