# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-13 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0016_auto_20180413_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
