# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-13 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0017_auto_20180413_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
