# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 06:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0018_auto_20180413_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.date(2018, 5, 14), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.TimeField(default=datetime.time(12, 29, 56, 937534), null=True),
        ),
    ]
