# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0019_auto_20180514_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 5, 14, 7, 6, 24, 181674, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2018, 5, 14, 7, 6, 34, 703304, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
