# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 07:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0020_auto_20180514_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.date(2018, 5, 14)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.TimeField(default=datetime.time(12, 55, 7, 745244)),
        ),
    ]
